name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan "${{ secrets.EC2_PUBLIC_DNS }}" >> ~/.ssh/known_hosts

    - name: SSH and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@"${{secrets.EC2_PUBLIC_DNS}}" << EOF
          git clone https://${{ secrets.REPO_CLONE_ACCESS_TOKEN }}@github.com/mahesh-jackett/actions.git
          cd ./actions
          git pull https://${{ secrets.REPO_CLONE_ACCESS_TOKEN }}@github.com/mahesh-jackett/actions.git
          docker stop fastapi_container
          docker rm fastapi_container
          docker build -t fastapi_image .
          docker run -d --name fastapi_container -p 8000:8000 fastapi_image
        EOF
